<?php $invoice = $this->getInvoice(); ?>
<div class="page-title">
    <h1><?php echo $this->__('Overdue Payments') ?></h1>
    <h3><?php echo $this->__('Invoice# ' . $invoice->getIncrementId()) ?></h3>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('folio3.overdue.invoice.info'); ?>
<br />

<?php if($invoice): ?>
    <?php echo $this->getChildHtml('folio3.overdue.invoice.payment'); ?>
<?php endif; ?>
